import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { quizApi, profileApi } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Loader2, Play, Sparkles, Trophy, BookOpen, Clock, Layers, Activity, Award, ArrowRight } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { motion, AnimatePresence } from "framer-motion";

export default function QuizList() {
  const { user, isLoggedIn } = useAuth();
  const navigate = useNavigate();
  const [quizzes, setQuizzes] = useState<Array<Record<string, unknown>>>([]);
  const [loading, setLoading] = useState(true);
  const [results, setResults] = useState<Array<Record<string, any>>>([]);
  const [profile, setProfile] = useState<Record<string, any> | null>(null);
  
  // AI Generation State
  const [isGenerating, setIsGenerating] = useState(false);
  const [isOpen, setIsOpen] = useState(false);
  const [aiTitle, setAiTitle] = useState("");
  const [aiCategory, setAiCategory] = useState("");
  const [aiNumQ, setAiNumQ] = useState(10);
  const [aiDifficulty, setAiDifficulty] = useState("Medium");

  const fetchData = async () => {
    if (!user?.email) return;
    try {
      setLoading(true);
      const p = await profileApi.getByEmail(user.email);
      setProfile(p);
      
      if (p.id) {
        const [quizData, resultData] = await Promise.all([
          quizApi.getForUser(p.id as number),
          profileApi.getQuizResults(p.id as number).catch(() => []),
        ]);
        
        const sortedQuizzes = (quizData as any[]).sort((a, b) => 
          (a.title as string || "").localeCompare(b.title as string || "")
        );
        
        setQuizzes(sortedQuizzes);
        setResults((resultData as any[]) || []);
      }
    } catch (err) {
      toast({ title: "Error", description: "Failed to load quizzes", variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!isLoggedIn) {
      navigate("/auth");
      return;
    }
    if (user?.id) {
       fetchData();
    }
  }, [user?.id, isLoggedIn, navigate]);

  const handleGenerateAI = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!aiTitle || !aiCategory) {
      toast({ title: "Error", description: "Please fill in all fields", variant: "destructive" });
      return;
    }
    
    setIsGenerating(true);
    try {
      await quizApi.generateQuiz({
        title: aiTitle,
        category: aiCategory,
        numQ: aiNumQ,
        creatorId: user?.id
      }, aiDifficulty);
      
      toast({ title: "Success", description: "Quiz generated by AI successfully!" });
      setIsOpen(false);
      setAiTitle("");
      setAiCategory("");
      fetchData();
    } catch (err) {
      toast({ title: "Error", description: "Failed to generate AI quiz", variant: "destructive" });
    } finally {
      setIsGenerating(false);
    }
  };

  if (loading) return (
    <div className="h-full flex items-center justify-center">
      <Loader2 className="w-12 h-12 animate-spin text-primary" />
    </div>
  );

  return (
    <div className="space-y-8 pb-12">
      {/* Recent Results Section */}
      {results.length > 0 && (
        <section className="animate-in fade-in slide-in-from-top-4 duration-500">
          <div className="flex items-center gap-3 mb-6">
             <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
                <Activity className="w-5 h-5 text-primary" />
             </div>
             <div>
                <h2 className="text-xl font-black text-foreground">Current Progress</h2>
                <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest">Recent Feats & Achievements</p>
             </div>
             <Dialog>
               <DialogTrigger asChild>
                 <Button variant="ghost" className="ml-auto text-primary font-bold gap-2 rounded-xl hover:bg-primary/5">
                   View All <ArrowRight className="w-4 h-4" />
                 </Button>
               </DialogTrigger>
               <DialogContent className="sm:max-w-[600px] max-h-[80vh] overflow-y-auto bg-white border-border p-8 rounded-[2rem] shadow-2xl">
                 <DialogHeader className="mb-6">
                   <DialogTitle className="text-2xl font-black flex items-center gap-3 text-foreground">
                     <Activity className="w-8 h-8 text-primary" />
                     Complete History
                   </DialogTitle>
                 </DialogHeader>
                 <div className="space-y-3">
                   {results.map((r, i) => {
                     const percent = Math.round((Number(r.score) / (Number(r.totalScore) || 10)) * 100);
                     return (
                       <div key={i} className="flex items-center justify-between p-4 rounded-2xl bg-muted/30 border border-border/50">
                         <div className="flex items-center gap-4">
                           <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${percent >= 70 ? 'bg-green-50' : 'bg-orange-50'}`}>
                             <Trophy className={`w-5 h-5 ${percent >= 70 ? 'text-green-600' : 'text-orange-500'}`} />
                           </div>
                           <div>
                             <p className="font-black text-sm text-foreground">{r.title || "Untitled Quiz"}</p>
                             <p className="text-[10px] font-bold text-muted-foreground uppercase">{new Date(r.dateTaken).toLocaleString()}</p>
                           </div>
                         </div>
                         <div className="text-right">
                           <span className={`text-lg font-black ${percent >= 70 ? 'text-green-600' : 'text-orange-500'}`}>{percent}%</span>
                         </div>
                       </div>
                     );
                   })}
                 </div>
               </DialogContent>
             </Dialog>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
             {results.slice(0, 3).map((r, i) => {
                const percent = Math.round((Number(r.score) / (Number(r.totalScore) || 10)) * 100);
                return (
                  <motion.div 
                    key={i} 
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.1 }}
                    className="bg-white border border-border p-4 rounded-2xl flex items-center justify-between shadow-sm hover:shadow-md transition-shadow"
                  >
                     <div className="flex items-center gap-3">
                        <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${percent >= 70 ? 'bg-green-50' : 'bg-orange-50'}`}>
                           <Trophy className={`w-5 h-5 ${percent >= 70 ? 'text-green-600' : 'text-orange-500'}`} />
                        </div>
                        <div className="max-w-[150px]">
                           <p className="text-xs font-black truncate">{r.title || "Untitled Quiz"}</p>
                           <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-tighter">
                              {new Date(r.dateTaken).toLocaleDateString()}
                           </p>
                        </div>
                     </div>
                     <div className="text-right">
                        <p className={`text-lg font-black ${percent >= 70 ? 'text-green-600' : 'text-orange-500'}`}>{percent}%</p>
                        <p className="text-[9px] font-black text-muted-foreground uppercase">SCORE</p>
                     </div>
                  </motion.div>
                );
             })}
          </div>
        </section>
      )}

      {/* Header */}
      <section className="flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <h1 className="text-4xl font-black tracking-tight text-foreground">Available Quizzes</h1>
          <p className="text-muted-foreground font-medium mt-1">Test your skills and challenge your intellect.</p>
        </div>
        
        <Dialog open={isOpen} onOpenChange={setIsOpen}>
          <DialogTrigger asChild>
            <Button className="rounded-2xl h-14 px-8 brand-gradient shadow-xl glow-primary active:scale-95 transition-all font-black text-lg gap-3">
              <Sparkles className="w-6 h-6 fill-white animate-pulse" />
              GENERATE NEW QUIZ
            </Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-[450px] bg-white border-border p-8 rounded-[3rem] shadow-2xl">
            <DialogHeader>
              <DialogTitle className="text-2xl font-black flex items-center gap-3 text-foreground">
                <Sparkles className="w-8 h-8 text-primary fill-primary" />
                AI Quiz Architect
              </DialogTitle>
            </DialogHeader>
            <form onSubmit={handleGenerateAI} className="space-y-6 pt-6">
              <div className="space-y-2">
                <Label className="text-[10px] uppercase font-black tracking-[0.2em] text-muted-foreground ml-2">Quiz Theme</Label>
                <Input placeholder="e.g. Advanced Quantum Computing" value={aiTitle} onChange={(e) => setAiTitle(e.target.value)} className="h-12 rounded-xl bg-muted/50 border-border font-bold text-foreground" />
              </div>
              <div className="space-y-2">
                <Label className="text-[10px] uppercase font-black tracking-[0.2em] text-muted-foreground ml-2">Knowledge Space</Label>
                <Input placeholder="e.g. Theoretical Physics" value={aiCategory} onChange={(e) => setAiCategory(e.target.value)} className="h-12 rounded-xl bg-muted/50 border-border font-bold text-foreground" />
              </div>
              <div className="grid grid-cols-2 gap-6">
                <div className="space-y-2">
                  <Label className="text-[10px] uppercase font-black tracking-[0.2em] text-muted-foreground ml-2">Questions</Label>
                  <Input type="number" min={5} max={30} value={aiNumQ} onChange={(e) => setAiNumQ(Number(e.target.value))} className="h-12 rounded-xl bg-muted/50 border-border font-bold text-foreground" />
                </div>
                <div className="space-y-2">
                  <Label className="text-[10px] uppercase font-black tracking-[0.2em] text-muted-foreground ml-2">Difficulty</Label>
                  <Select value={aiDifficulty} onValueChange={setAiDifficulty}>
                    <SelectTrigger className="h-12 rounded-xl bg-muted/50 border-border font-bold text-foreground">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Easy">Beginner</SelectItem>
                      <SelectItem value="Medium">Intermediate</SelectItem>
                      <SelectItem value="Hard">Advanced</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <Button type="submit" className="w-full h-14 rounded-2xl brand-gradient font-black text-white text-lg glow-primary shadow-lg shadow-primary/20" disabled={isGenerating}>
                {isGenerating ? (
                  <><Loader2 className="w-5 h-5 animate-spin mr-3" /> ARCHITECTING...</>
                ) : (
                  "CONSTRUCT QUIZ"
                )}
              </Button>
            </form>
          </DialogContent>
        </Dialog>
      </section>

      {/* Quiz Bento Grid */}
      <AnimatePresence>
      {quizzes.length === 0 ? (
        <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="h-80 border-2 border-dashed border-border rounded-[3rem] flex flex-col items-center justify-center text-muted-foreground space-y-4 bg-muted/20"
        >
          <BookOpen className="w-16 h-16 opacity-10" />
          <p className="font-black uppercase tracking-[0.3em] text-xs">Vault Empty</p>
          <Button variant="outline" onClick={() => setIsOpen(true)} className="rounded-xl border-border bg-white hover:bg-muted text-foreground font-bold">Start First Session</Button>
        </motion.div>
      ) : (
        <div className="bento-grid">
          {quizzes.map((q, i) => (
            <motion.div 
              key={q.id as number}
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: i * 0.05 }}
              className="bento-item group relative overflow-hidden flex flex-col justify-between min-h-[280px] bg-white hover:shadow-2xl border-border"
            >
              <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 rounded-full blur-3xl -mr-16 -mt-16 group-hover:bg-primary/10 transition-all" />
              
              <div>
                <div className="flex items-center justify-between mb-6">
                   <div className="w-12 h-12 rounded-2xl bg-primary/5 flex items-center justify-center border border-primary/5 group-hover:border-primary/40 transition-colors">
                      <Trophy className="text-secondary-foreground w-6 h-6 text-primary fill-primary/20" />
                   </div>
                   <div className="flex gap-2">
                       {results.some(r => r.quiz?.id === q.id) && (
                           <div className="px-3 py-1 rounded-full bg-green-500/10 text-[10px] font-black uppercase tracking-tighter text-green-600 border border-green-500/20 flex items-center gap-1">
                               <Award className="w-3 h-3" />
                               Attempted
                           </div>
                       )}
                       <div className="px-3 py-1 rounded-full bg-muted text-[10px] font-black uppercase tracking-tighter text-muted-foreground group-hover:bg-primary/10 group-hover:text-primary transition-colors">
                          {q.category as string}
                       </div>
                   </div>
                </div>

                <h3 className="text-xl font-black mb-1 line-clamp-2 leading-tight group-hover:text-primary transition-colors h-14 text-foreground">{q.title as string}</h3>
                
                <div className="flex gap-4 mt-6">
                    <div className="flex items-center gap-2">
                        <Layers className="w-3 h-3 text-muted-foreground" />
                        <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">{q.numQ as number} Qs</span>
                    </div>
                    <div className="flex items-center gap-2">
                        <Clock className="w-3 h-3 text-muted-foreground" />
                        <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">15 Mins</span>
                    </div>
                </div>
              </div>

              <div className="mt-8">
                <Link to={`/take-quiz/${q.id}`}>
                  <Button 
                    className={`w-full h-14 rounded-2xl transition-all font-black uppercase tracking-widest text-[10px] ${
                      results.some(r => r.quiz?.id === q.id)
                      ? "bg-green-50/50 border-green-100 text-green-600 hover:bg-green-600 hover:text-white"
                      : "bg-muted/50 border-border text-muted-foreground hover:brand-gradient hover:border-transparent hover:text-white"
                    } border group/btn active:scale-95`}
                  >
                    {results.some(r => r.quiz?.id === q.id) ? "RE-ATTEMPT SESSION" : "LAUNCH SESSION"}
                    <Play className="ml-2 w-3.5 h-3.5 fill-current group-hover/btn:scale-110" />
                  </Button>
                </Link>
              </div>
            </motion.div>
          ))}
        </div>
      )}
      </AnimatePresence>
    </div>
  );
}
